imnodes = '''
[editor]
panning=-42,-44

[node.1]
origin=764,182

'''

imnodes_graph = '''
{"nodes": [{"id": 1, "title": "bvh", "inputs": [], "outputs": []}], "links": [], "next_id": 2}
'''

imgui = '''
[Window][__DOCKING_SPACE__]
Pos=0,0
Size=2690,1792
Collapsed=0

[Window][pose_graph]
Pos=158,26
Size=2532,1579
Collapsed=0
DockId=0x00000002,0

[Window][Dear ImGui Metrics/Debugger]
Pos=0,26
Size=156,1579
Collapsed=0
DockId=0x00000001,0

[Window][log]
Pos=0,1607
Size=2690,185
Collapsed=0
DockId=0x00000004,0

[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Docking][Data]
DockSpace     ID=0x70311316 Window=0x4C7182C2 Pos=0,26 Size=2690,1766 Split=Y
  DockNode    ID=0x00000003 Parent=0x70311316 SizeRef=1024,555 Split=X
    DockNode  ID=0x00000001 Parent=0x00000003 SizeRef=156,742 Selected=0x20E3C5EA
    DockNode  ID=0x00000002 Parent=0x00000003 SizeRef=1179,742 CentralNode=1 Selected=0xD94BA58A
  DockNode    ID=0x00000004 Parent=0x70311316 SizeRef=1024,185 Selected=0xAB483779


'''

glfw = '''
{"width": 2690, "height": 1792, "is_maximized": false}
'''

